#-------------------------------------
# Path to sample sheet
#-------------------------------------

sample: sample.tsv

#-------------------------------------
# Config
#-------------------------------------
rules:
    # Optimizing and assembling genome annotations for 3’ single-cell RNA-sequencing analysis
    reference_enhancer_rule: "FALSE"
    # Build the reference with cellranger
    ref_cellranger_rule: "FALSE"
    # Demultiplexing
    multi_rule: "TRUE"
       
run:
    # FASTQ file naming convention : [Sample name]_S1_L00[Lane Number]_[Read Type]_001.fastq.gz
    
    # Can be a list if pair-end : "R1,R2" or "1,2" or "R1_001,R2_001"
    types: "1,2"
    # Library if multiplexed 
    library: "1_A_GEX,2_A_CMO"

fastq:
    # Expension of fastq file
    expansion: "fastq"
    # pair-end or not (R1,R2 or 1,2 etc...)
    pair: "R1,R2"
    # Bioproject
    biop: "SRP215051_SRP287614"
    # Sequence Read Archive (SRA)
    sra: "SRP287614"
    # Sample name ; Multiple names may be supplied as a comma-separated list, in which case they will be treated as one sample.
    sname: "72h,80h,86h,96h"
    # Project name
    nproject: "SRP215051_SRP287614"

# Genome and gff link to create the pre-built Cell Ranger reference
reference:
    link_ref_fasta: "https://ftp.ensembl.org/pub/release-98/fasta/mus_musculus/dna/Mus_musculus.GRCm38.dna.primary_assembly.fa.gz"
    # link_ref_fasta: "https://ftp.ensembl.org/pub/release-109/fasta/mus_musculus/dna/Mus_musculus.GRCm39.dna.primary_assembly.fa.gz"
    ref_gtf: "Mus_musculus.GRCm39.109.gtf"
    link_ref_gtf: "https://storage.googleapis.com/generecovery/mouse_mm10_optimized_annotation_v2.gtf.gz"
    # link_ref_gtf: "https://ftp.ensembl.org/pub/release-109/gtf/mus_musculus/Mus_musculus.GRCm39.109.gtf.gz"
    ref_fasta: "Mus_musculus.GRCm38.dna.primary_assembly.fa"
    # ref_fasta: "Mus_musculus.GRCm39.dna.primary_assembly.fa"
    # Name for the file of the cellranger reference
    ref_cellranger: "refdata-cellranger-mm10"
    # ref_cellranger: "refdata-cellranger-mm32"
    # Optional reference version string to include with
    ref_version: "1.0.0"

# Parameter for cellranger multi
multi:
    # A unique run ID string: e.g. sample345 that is also the output folder name. Cannot be more than 64 characters.
    id: "S004647_to_S004650"
    # Path to config CSV file with input libraries and analysis parameters.
    config: "multi_config.csv"

# parameter for cellranger count
cellranger:
    # Path of the fastq_path folder. Can take multiple comma-separated paths, which is helpful if the same library was sequenced on multiple flowcells. 
    fastqs: "00_RawData"
    # Expected number of recovered cells. Default: 3,000 cells.
    cells: 5000
    # Restricts cellranger to use specified number of cores to execute pipeline stages
    localcores: 6
    # Restricts cellranger to use specified amount of memory (in GB) to execute pipeline stages.
    localmem: 50
    # Sample to be aggregated by cell ranger
    sagrr: "M12,M15,M27,Normal_Melanocytes,Mix_MM_lines"
    # Aggregating libraries with different chemistry versions. Need to be in the same order than sagrr.
    batch: "v3_lib,v3_lib,v3_lib,v3_lib,v3_lib"
    # Assign categories to individual samples. Need to be in the same order than sagrr.
    categorie: "melanoma,melanoma,melanoma,normal,melanoma"
    # Depth normalization for aggregate ("none" or "mapped"). The none option may be appropriate if you want to maximize sensitivity and plan to deal with depth normalization in a downstream step.
    normagrr: "none"
    demuxlet:
    # Tell if multiple samples are pooled by barcoded single cell sequencing and need deconvolute sample identity and identify multiplets.
    spooled: "TRUE"

# Seurat parameters
seurat:
    ##### General

    # Number of cells above which use ggplot instead of interactive plotly
    plot_raster_nbcells_threshold : 10000
    # CellRanger count path for each sample for Read10X
    cell-ranger_count_path: "/count/sample_filtered_feature_bc_matrix/"

    ##### Filtering 

    # Switch from QC exploration mode and QC filtering
    # In exploration mode, the cells that would be filtered by QC threshold are not filtered but marked
    # They are shown in the later analysis with a different color
    # "TRUE" : Exploration mode, "FALSE" : Not in exploration mode
    qc_exploration_mode: "FALSE"

    # Include features detected in at least this many cells. Will subset the counts matrix as well.
    min_cells: 3

    # Include cells where at least this many features are detected.
    min_features: 200

    # Cells with number of UMIs outside the range will be excluded
    # Can be a list of UMIs but MUST be on the same order than sample.tsv id.
    filter_umi_min: "0,0,0,0"
    filter_umi_max: "50000,40000,40000,40000"

    # Filter cells that have unique feature counts over/less n
    # Can be a list of feature counts but MUST be on the same order than sample.tsv id.
    filter_feature_min: "1800,1800,1500,1500"
    filter_feature_max: "7700,7500,7700,7200"

    # Filter cells that have > n% mitochondrial counts
    filter_percent_mt: "10,10,8,8"
    # Filter cells that have < n% mitochondrial counts
    filter_percent_mt_min: "1,1,0,0"

    # Filter cells that have < n% ribosomal counts
    filter_percent_rb: "0,0,0,0"

    # Pattern to match features against => mitochondrial genes | for mouse : "^mt-" / for human : "^MT-"
    pattern_mt: "^mt-"

    # Pattern to match features against => ribosomal genes
    pattern_rb: "^rps|^rpl"

    ##### Normalization

    # Normalization parameters (see Seurat::NormalizeData())
    norm_method: "LogNormalize"
    norm_scale_factor: 10000

    ##### Find the most variable genes

    # How to choose top variable features => vst, mean.var.plot or dispersion
    feature_select_method: "vst"

    # Number of features to select as top variable features; only used when select_method is set to 'dispersion' or 'vst'
    variable_features: 2000

    # For table in report
    variable_features_showtop : 200
    
    ##### PCA parameters
    # Number of dimention to show for the vizualisation
    dims: 30

    # Default number of dimensions to use for PCA (see Seurat::RunPCA())
    pca_npc: 20

    # Number of dimensions to show in PCA-related plots
    pca_plots_nbdims : 3

    #  Number of'top' features to show when plotting PCA loadings
    pca_plot_nbfeatures : 3

    ##### Dimensionality reduction parameters (TSNE/UMAP)

    # Number of dimensions to use from PCA results
    dimreduc_use_pca_nbdims : 20

    ##### Cluster identification parameters

    # Number of dimensions to use from PCA results
    findclusters_use_pca_nbdims : 20

    # Nearest-neighbor graph construction
    findneighbors_k : 30

    # Value of the resolution parameter, use a value above (below) 1.0 if you want to obtain a larger (smaller) number of communities.
    findclusters_resolution : 1

    # Algorithm for modularity optimization
    # 1 = Louvain; 2 = Louvain with multilevel refinement; 3 = SLM; 4 = Leiden
    findclusters_algorithm : 1

# Differentially expressed features analyses
diffexp:
    # Features of interest
    features: "SOX10,SOX9,RIPOR2,MITF,DCT,MYC,FLT1,TNFRSF11B,XIRP2,ST3GAL1"
    # Cells of interest to find differentially expressed features against "Normal" or Wild Type cells
    cell_marker: "M12,M15,M27,MM029,A375,MM031,MM057,MM099,MM087,MM001,MM074,MM011,MM047"
    # Test to find differentially expressed genes. Can be wilcox, bimod, roc, t, negbinom, poisson, LR, MAST, DESeq2.
    test: "wilcox"
    # Threshold to detect the under or over expressed genes
    threshold: 0.0
    # qvalue threshold
    pCutoff: 0.01
    # Foldchange threshold (not in log base 2)
    FCcutoff: 2
# Differentially expressed features analyses inside cluster after subset (by gene expression)
diffexpsubset:
    # Marker of interest to select cluster of Cells with expression or not of this gene. This gene will be removed for the DE analyses due to is high DE value.
    marker_gene: "RIPOR2"
    # If no gene indicated this filter is not performed.
    genetoremove: ""
    # Cluster on the seurat object (choose cluster with high number of the marker gene of interest)
    cluster: "Normal_Melanocytes,M15,M27,A375,MM057,MM087,MM001,MM074"
    
