
# path or URL to condition sheet (TSV format)
metadata: sample-metadata.tsv

sample:
    # Expension of fastq file
    expansion: "fastq"
    # pair-end or not (R1,R2 or 1,2 etc...)
    pair: "R1,R2"
    # Bioproject
    biop: "SRP215051_SRP287614"
    # Sequence Read Archive (SRA)
    sra: "SRP287614"
    # Sample name ; Multiple names may be supplied as a comma-separated list, in which case they will be treated as one sample.
    sname: "M12,M15,M27,Normal_Melanocytes,Mix_MM_lines"
    # Project name
    nproject: "SRP215051_SRP287614"

# Genome and gff link to create the pre-built Cell Ranger reference
reference:
    link_ref_fasta: "http://ftp.ensembl.org/pub/release-104/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz"
    ref_fasta: "Homo_sapiens.GRCh38.dna.primary_assembly.fa"
    link_ref_gff: "http://ftp.ensembl.org/pub/release-104/gtf/homo_sapiens/Homo_sapiens.GRCh38.104.gtf.gz"
    # Name for the file of the cellranger reference
    ref_cellranger: "refdata-cellranger-hg19-6.0.0"
    ref_version: "6.0.0"

    # parameter for cellranger count
cellranger:
    # Path of the fastq_path folder. Can take multiple comma-separated paths, which is helpful if the same library was sequenced on multiple flowcells. 
    fastqs: "00_RawData"
    # Expected number of recovered cells. Default: 3,000 cells.
    cells: 5000
    # Restricts cellranger to use specified number of cores to execute pipeline stages
    localcores: 6
    # Restricts cellranger to use specified amount of memory (in GB) to execute pipeline stages.
    localmem: 50
    # Sample to be aggregated by cell ranger
    sagrr: "M12,M15,M27,Normal_Melanocytes,Mix_MM_lines"
    # Aggregating libraries with different chemistry versions. Need to be in the same order than sagrr.
    batch: "v3_lib,v3_lib,v3_lib,v3_lib,v3_lib"
    # Assign categories to individual samples. Need to be in the same order than sagrr.
    categorie: "melanoma,melanoma,melanoma,normal,melanoma"
    # Depth normalization for aggregate ("none" or "mapped"). The none option may be appropriate if you want to maximize sensitivity and plan to deal with depth normalization in a downstream step.
    normagrr: "none"
    demuxlet:
    # Tell if multiple samples are pooled by barcoded single cell sequencing and need deconvolute sample identity and identify multiplets.
    spooled: "TRUE"
# Seurat parameters
seurat:
    # Name of the "Normal" or Wild Type sample to group samples for the comparison
    wt: "Normal_Melanocytes"
    # Include features detected in at least this many cells. Will subset the counts matrix as well. To reintroduce excluded features, create a new object with a lower cutoff.
    min_cells: 3
    # Include cells where at least this many features are detected.
    min_features: 200
    ## To be fixed after the visualization of the QC metrics as a violin plot and FeatureScatter
    # Filter cells that have unique feature counts less n.
    minFeature_RNA: 200
    # Filter cells that have unique feature counts over n. Value have to be selected via the plot nCount_RNA/nfeature_RNA
    # Can be a list of feature counts but MUST be on the same order than [cellranger][sagrr]
    maxFeature_RNA: "3000,10200,7700,8000,7000"
    # Filter cells that have >20% mitochondrial counts
    percent_mt: 20
    # Normalization workflow used by seurat (for batch effect correction). Can be "SCTransform" (calculates a model of technical noise in scRNA-seq data using ‘regularized negative binomial regression’) or "basictransform" (run NormalizeData, FindVariableFeatures, ScaleData steps).
    normwf: "SCTransform"
    # Use this many features as variable features after ranking by residual variance
    # If basictransform is used :Method for normalization (LogNormalize, CLR (centered log ratio transformation) or RC (Relative counts))
    normalization_method: "LogNormalize"
    # Sets the scale factor for cell-level normalization
    scale_factor: 10000
    # How to choose top variable features (vst, mean.var.plot or dispersion)
    selection_method: "vst" 
    # Number of features to select as top variable features
    nfeatures: 3000
    # Number of highly variable genes label
    nHVG: 20
    # Dimension for the clustering (look the elbow plot to fix it)
    dims: 12
    # Resolution parameter for the clustering (Higher resolution means higher number of clusters)
    resolution: 0.08
    # Assigning cell type identity to clusters
    cluster_ids: "MM029,A375,MM031,MM057,MM099,MM087,MM001,MM074,MM011,MM047"
# Differentially expressed features analyses
diffexp:
    # Features of interest
    features: "SOX10,SOX9,RIPOR2,MITF,DCT,MYC,FLT1,TNFRSF11B,XIRP2,ST3GAL1"
    # Cells of interest to find differentially expressed features against "Normal" or Wild Type cells
    cell_marker: "M12,M15,M27,MM029,A375,MM031,MM057,MM099,MM087,MM001,MM074,MM011,MM047"
    # Test to find differentially expressed genes. Can be wilcox, bimod, roc, t, negbinom, poisson, LR, MAST, DESeq2.
    test: "wilcox"
    # Threshold to detect the under or over expressed genes
    threshold: 0.0
    # qvalue threshold
    pCutoff: 0.01
    # Foldchange threshold (not in log base 2)
    FCcutoff: 2
# Differentially expressed features analyses inside cluster after subset (by gene expression)
diffexpsubset:
    # Marker of interest to select cluster of Cells with expression or not of this gene. This gene will be removed for the DE analyses due to is high DE value.
    marker_gene: "RIPOR2"
    # If no gene indicated this filter is not performed.
    genetoremove: ""
    # Cluster on the seurat object (choose cluster with high number of the marker gene of interest)
    cluster: "Normal_Melanocytes,M15,M27,A375,MM057,MM087,MM001,MM074"
    
