$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  sample:
    type: object
    properties:
      sname:
        type: string
      biop:
        type: string
      sra:
        type: string
    required:
      - sname
      - biop
  reference:
    type: object
    properties:
      link_ref_fasta:
        type: string
      link_ref_gff:
        type: string
      ref_cellranger:
        type: string
      ref_version:
        type: string

    required:
      - link_ref_fasta
      - link_ref_gff
      - ref_cellranger
      - ref_version
  
  cellranger:
    type: object
    properties:
      fastqs:
        type: string
      cells:
        type: integer
      localcores:
        type: integer
      localmem:
        type: integer
    required:
      - fastqs
      - cells
      - localcores
      - localmem

  demuxlet:
    type: object
    properties:
      spooled:
        type: string
    required:
      - spooled

  seurat:
    type: object
    properties:
      merge:
        type: string
      smerge:
        type: string
      min_cells:
        type: integer
      min_features:
        type: integer
      minFeature_RNA:
        type: integer
      maxFeature_RNA:
        type: integer
      percent_mt:
        type: integer
      normwf:
        type: string
      normalization_method:
        type: string
      scale_factor:
        type: integer
      selection_method:
        type: string
      nfeatures:
        type: integer
      nHVG:
        type: integer
      dims:
        type: integer
      expclust:
        type: integer
      cluster_ids:
        type: string
    required:
      - merge
      - min_cells
      - min_features
      - minFeature_RNA
      - maxFeature_RNA
      - percent_mt
      - normwf
      - normalization_method
      - scale_factor
      - selection_method
      - nfeatures
      - nHVG
      - dims
      - expclust
  diffexp:
    type: object
    properties:
      features:
        type: string
    required:
      - features
